# Generated by Django 2.1.5 on 2019-01-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IslandGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=10)),
                ('desc', models.CharField(max_length=300)),
                ('resp', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='RandomEncountersLand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=10)),
                ('desc', models.CharField(max_length=300)),
                ('resp', models.CharField(max_length=600)),
                ('loottrg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RandomEncountersSea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=10)),
                ('desc', models.CharField(max_length=300)),
                ('resp', models.CharField(max_length=600)),
                ('loottrg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RandomLootLarge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=10)),
                ('desc', models.CharField(max_length=300)),
                ('resp', models.CharField(max_length=600)),
                ('lootvalue', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RandomLootSmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=10)),
                ('desc', models.CharField(max_length=300)),
                ('resp', models.CharField(max_length=600)),
                ('lootvalue', models.IntegerField(max_length=10)),
            ],
        ),
    ]
