# Generated by Django 2.1.5 on 2019-01-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googlepirate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islandgenerator',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='randomencountersland',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='randomencounterssea',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='randomlootlarge',
            name='lootvalue',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='randomlootlarge',
            name='num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='randomlootsmall',
            name='lootvalue',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='randomlootsmall',
            name='num',
            field=models.IntegerField(),
        ),
    ]
