# Generated by Django 2.1.5 on 2019-01-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googlepirate', '0003_auto_20190120_0852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DialogFlowData',
        ),
    ]
